import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Search, ChevronDown, ArrowRight, MessageCircle } from 'lucide-react';
import { PageHeader } from '../components/PageLayout';

const articles = [
  { category: 'Buying & renting', question: 'How do I find a car?', answer: 'Use Buy cars or Rent cars in the navigation. Search by make or model, choose your location and budget, and use More filters for condition, year and verified sellers. Open a listing to see photos and specifications.' },
  { category: 'Buying & renting', question: 'How do I contact a seller or arrange a viewing?', answer: 'Open the car’s listing and select Message seller. Sign in to send your message. You can also use the seller’s phone or WhatsApp link when provided. Agree on a suitable viewing time and location directly with the seller.' },
  { category: 'Buying & renting', question: 'What happens when I submit a purchase or rental request?', answer: 'We save your request and show it in your dashboard and the seller’s dashboard. No vehicle payment is collected on this site. Confirm availability, rental dates, options and final payment arrangements with the seller.' },
  { category: 'Buying & renting', question: 'How do saved cars and comparisons work?', answer: 'Sign in and choose Save car on a listing to add it to Saved cars. Select Compare on up to three cars to review their prices and specifications together. Comparison is also available while signed out.' },
  { category: 'Safety', question: 'What should I check before paying for a car?', answer: 'Inspect the vehicle in person, check its documents and ownership history, and consider an independent mechanic. Meet at the dealership or in a public place. Don’t send money before checking the vehicle and seller.' },
  { category: 'Safety', question: 'What does a verified seller badge mean?', answer: 'The badge indicates that the seller profile has been marked as verified by NaijaCars. It is not a vehicle inspection, warranty or guarantee of a transaction. Always carry out your own checks.' },
  { category: 'Selling', question: 'How do I list my car?', answer: 'Create an account, verify your email and choose an active seller plan. Select List a car, enter the vehicle details, upload photos, set the price and location, then review and submit. You can manage and edit listings from your dashboard.' },
  { category: 'Selling', question: 'Do I need a subscription to sell?', answer: 'Yes. An active seller subscription with an available listing allowance is required to publish a new listing. Current plans and allowances appear on the Seller plans page. Browsing cars is free.' },
  { category: 'Selling', question: 'Can I change my listing after publishing?', answer: 'Open Dashboard, choose My listings and select Edit on the vehicle. Update the details or photos and save. Your listing remains available while you prepare changes.' },
  { category: 'Account', question: 'How do I reset my password?', answer: 'Open Sign in and select Forgot password. Enter your email address, then use the reset code sent to you to set a new password. If you are signed in, you can change your password under Account settings → Security.' },
  { category: 'Account', question: 'Where can I find my messages and requests?', answer: 'Messages are available from your account menu. Purchase and rental requests appear in the Requests tab of your dashboard. Notifications show recent message activity.' },
  { category: 'Account', question: 'How do I update my profile or verify my account?', answer: 'Open Account settings to update your name, phone, location, bio and profile photo. Use the Verification tab to request an email code and confirm your account.' },
];
export default function HelpPage() {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('All topics');
  const results = articles.filter(article => (category === 'All topics' || article.category === category) && `${article.question} ${article.answer}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeader eyebrow="NaijaCars help centre" title="A little guidance for your next move." description="Find answers about buying, renting, selling and your account." /><div className="nc-page-width nc-content nc-help-content"><div className="nc-help-search"><Search size={20} /><input type="search" aria-label="Search help articles" placeholder="What would you like help with?" value={query} onChange={(e) => setQuery(e.target.value)} /></div><div className="nc-help-topics">{['All topics', 'Buying & renting', 'Selling', 'Safety', 'Account'].map(item => <button key={item} aria-pressed={category === item} onClick={() => setCategory(item)}>{item}</button>)}</div>
    <p className="text-sm text-muted mb-5">{results.length} {results.length === 1 ? 'answer' : 'answers'}</p><div className="nc-help-articles">{results.map(article => <details key={article.question} className="nc-panel"><summary>{article.question}<ChevronDown size={19} /></summary><p>{article.answer}</p></details>)}</div>{!results.length && <div className="nc-panel"><h2>No answers found</h2><p className="nc-description">Try another search or contact us for help.</p><button className="nc-text-link" onClick={() => { setQuery(''); setCategory('All topics'); }}>Clear filters</button></div>}
    <div className="nc-about-cta"><div><MessageCircle size={25} className="text-brand mb-3" /><h2>Still need a hand?</h2><p>Send us a message and tell us what you need help with.</p></div><Link to="/contact" className="nc-button">Contact support<ArrowRight size={18} /></Link></div>
  </div></>;
}
